6. CI/CD Pipeline with GitHub Actions

name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: '1.27'

    - name: Deploy Kubernetes Manifests
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
